/*id 1*/
import {Mutation} from "@prisma/client";

export const trainingData: { target: Omit<Mutation, 'valeur_fonciere'>, X_train: Mutation[], Y_train: number[] } = {
    target: {
        adresse_code_voie: "",
        adresse_nom_voie: "",
        adresse_numero: 0,
        code_commune: 0,
        code_departement: 0,
        code_postal: 0,
        date_mutation: new Date(),
        id_mutation: "",
        latitude: 55.453943902864197,
        longitude: -20.88342939010915,
        nature_mutation: "",
        new_id_mutation: "",
        nom_commune: "",
        nombre_lots: 0,
        nombre_pieces_principales: 0,
        surface_reelle_bati: 0,
        type_local: ""
    },
    X_train: [
        /*id 2*/
        {
            date_mutation: new Date('2020-01-01'),
            valeur_fonciere: 100,
            surface_reelle_bati: 10,
            new_id_mutation: "",
            id_mutation: "",
            nature_mutation: "",
            adresse_numero: 0,
            adresse_nom_voie: "",
            adresse_code_voie: "",
            code_postal: 974,
            code_commune: 97418,
            nom_commune: "Sainte Marie",
            code_departement: 974,
            nombre_lots: 0,
            type_local: "Maison",
            nombre_pieces_principales: 0,
            longitude: -20.882643850777765,
            latitude: 55.456911495893863
        },
        {
            /*id 3*/
            date_mutation: new Date('2020-01-01'),
            valeur_fonciere: 200,
            surface_reelle_bati: 20,
            new_id_mutation: "",
            id_mutation: "",
            nature_mutation: "",
            adresse_numero: 0,
            adresse_nom_voie: "",
            adresse_code_voie: "",
            code_postal: 974,
            code_commune: 97418,
            nom_commune: "Sainte Marie",
            code_departement: 974,
            nombre_lots: 0,
            type_local: "Appartement",
            nombre_pieces_principales: 0,
            longitude: -20.883923988947426,
            latitude: 55.45603867441455
        },
        {
            /*4*/
            date_mutation: new Date('2020-01-01'),
            valeur_fonciere: 200,
            surface_reelle_bati: 20,
            new_id_mutation: "",
            id_mutation: "",
            nature_mutation: "",
            adresse_numero: 0,
            adresse_nom_voie: "",
            adresse_code_voie: "",
            code_postal: 974,
            code_commune: 97418,
            nom_commune: "Sainte Marie",
            code_departement: 974,
            nombre_lots: 0,
            type_local: "Appartement",
            nombre_pieces_principales: 0,
            longitude: -20.888200814196065,
            latitude: 55.454263937406608
        },
        {
            /*5*/
            date_mutation: new Date('2020-01-01'),
            valeur_fonciere: 200,
            surface_reelle_bati: 20,
            new_id_mutation: "",
            id_mutation: "",
            nature_mutation: "",
            adresse_numero: 0,
            adresse_nom_voie: "",
            adresse_code_voie: "",
            code_postal: 974,
            code_commune: 97418,
            nom_commune: "Sainte Marie",
            code_departement: 974,
            nombre_lots: 0,
            type_local: "Appartement",
            nombre_pieces_principales: 0,
            longitude: -20.886920676026403,
            latitude: 55.456155050611791
        },
        {
            /*6*/
            date_mutation: new Date('2020-01-01'),
            valeur_fonciere: 200,
            surface_reelle_bati: 20,
            new_id_mutation: "",
            id_mutation: "",
            nature_mutation: "",
            adresse_numero: 0,
            adresse_nom_voie: "",
            adresse_code_voie: "",
            code_postal: 974,
            code_commune: 97418,
            nom_commune: "Sainte Marie",
            code_departement: 974,
            nombre_lots: 0,
            type_local: "Appartement",
            nombre_pieces_principales: 0,
            longitude: -20.887531651061924,
            latitude: 55.457406094732143
        },
        {
            date_mutation: new Date('2020-01-01'),
            valeur_fonciere: 100,
            surface_reelle_bati: 20,
            new_id_mutation: "",
            id_mutation: "",
            nature_mutation: "",
            adresse_numero: 0,
            adresse_nom_voie: "",
            adresse_code_voie: "",
            code_postal: 974,
            code_commune: 97411,
            nom_commune: "Saint Denis",
            code_departement: 974,
            nombre_lots: 0,
            type_local: "Appartement",
            nombre_pieces_principales: 0,
            longitude: -20.887531651061924,
            latitude: 55.457406094732143
        }, {
            date_mutation: new Date('2020-01-01'),
            valeur_fonciere: 200,
            surface_reelle_bati: 20,
            new_id_mutation: "",
            id_mutation: "",
            nature_mutation: "",
            adresse_numero: 0,
            adresse_nom_voie: "",
            adresse_code_voie: "",
            code_postal: 974,
            code_commune: 97411,
            nom_commune: "Saint Denis",
            code_departement: 974,
            nombre_lots: 0,
            type_local: "Appartement",
            nombre_pieces_principales: 0,
            longitude: -20.887531651061924,
            latitude: 55.457406094732143
        },
    ],
    Y_train: []
}

export const trainingDataKmeans: {
    target: Omit<Mutation, 'valeur_fonciere'>,
    X_train: Mutation[],
    Y_train: number[]
} = {
    target: {
        adresse_code_voie: "",
        adresse_nom_voie: "",
        adresse_numero: 0,
        code_commune: 0,
        code_departement: 0,
        code_postal: 0,
        date_mutation: new Date(),
        id_mutation: "",
        latitude: 55.453943902864197,
        longitude: -20.88342939010915,
        nature_mutation: "",
        new_id_mutation: "",
        nom_commune: "",
        nombre_lots: 0,
        nombre_pieces_principales: 0,
        surface_reelle_bati: 0,
        type_local: ""
    },
    X_train: [
        /*id 2*/
        {
            date_mutation: new Date('2020-01-01'),
            valeur_fonciere: 100,
            surface_reelle_bati: 10,
            new_id_mutation: "",
            id_mutation: "",
            nature_mutation: "",
            adresse_numero: 0,
            adresse_nom_voie: "",
            adresse_code_voie: "",
            code_postal: 974,
            code_commune: 97411,
            nom_commune: "Sainte Denis",
            code_departement: 974,
            nombre_lots: 0,
            type_local: "Maison",
            nombre_pieces_principales: 0,
            longitude: -20.882643850777765,
            latitude: 55.456911495893863
        },
        {
            /*id 3*/
            date_mutation: new Date('2020-01-01'),
            valeur_fonciere: 200,
            surface_reelle_bati: 20,
            new_id_mutation: "",
            id_mutation: "",
            nature_mutation: "",
            adresse_numero: 0,
            adresse_nom_voie: "",
            adresse_code_voie: "",
            code_postal: 974,
            code_commune: 97411,
            nom_commune: "Sainte Denis",
            code_departement: 974,
            nombre_lots: 0,
            type_local: "Appartement",
            nombre_pieces_principales: 0,
            longitude: -20.883923988947426,
            latitude: 55.45603867441455
        },
        {
            /*4*/
            date_mutation: new Date('2020-01-01'),
            valeur_fonciere: 200,
            surface_reelle_bati: 20,
            new_id_mutation: "",
            id_mutation: "",
            nature_mutation: "",
            adresse_numero: 0,
            adresse_nom_voie: "",
            adresse_code_voie: "",
            code_postal: 974,
            code_commune: 97411,
            nom_commune: "Sainte Denis",
            code_departement: 974,
            nombre_lots: 0,
            type_local: "Appartement",
            nombre_pieces_principales: 0,
            longitude: -20.888200814196065,
            latitude: 55.454263937406608
        },
        {
            /*5*/
            date_mutation: new Date('2020-01-01'),
            valeur_fonciere: 200,
            surface_reelle_bati: 20,
            new_id_mutation: "",
            id_mutation: "",
            nature_mutation: "",
            adresse_numero: 0,
            adresse_nom_voie: "",
            adresse_code_voie: "",
            code_postal: 974,
            code_commune: 97411,
            nom_commune: "Sainte Denis",
            code_departement: 974,
            nombre_lots: 0,
            type_local: "Appartement",
            nombre_pieces_principales: 0,
            longitude: -20.886920676026403,
            latitude: 55.456155050611791
        },
        {
            /*6*/
            date_mutation: new Date('2020-01-01'),
            valeur_fonciere: 200,
            surface_reelle_bati: 20,
            new_id_mutation: "",
            id_mutation: "",
            nature_mutation: "",
            adresse_numero: 0,
            adresse_nom_voie: "",
            adresse_code_voie: "",
            code_postal: 974,
            code_commune: 97411,
            nom_commune: "Sainte Denis",
            code_departement: 974,
            nombre_lots: 0,
            type_local: "Appartement",
            nombre_pieces_principales: 0,
            longitude: -20.887531651061924,
            latitude: 55.457406094732143
        }, {
            date_mutation: new Date('2020-01-01'),
            valeur_fonciere: 200,
            surface_reelle_bati: 20,
            new_id_mutation: "",
            id_mutation: "",
            nature_mutation: "",
            adresse_numero: 0,
            adresse_nom_voie: "",
            adresse_code_voie: "",
            code_postal: 974,
            code_commune: 97418,
            nom_commune: "Sainte Marie",
            code_departement: 974,
            nombre_lots: 0,
            type_local: "Appartement",
            nombre_pieces_principales: 0,
            longitude: -20.895833904348127,
            latitude: 55.567016535601205
        }, {
            date_mutation: new Date('2020-01-01'),
            valeur_fonciere: 200,
            surface_reelle_bati: 20,
            new_id_mutation: "",
            id_mutation: "",
            nature_mutation: "",
            adresse_numero: 0,
            adresse_nom_voie: "",
            adresse_code_voie: "",
            code_postal: 974,
            code_commune: 97418,
            nom_commune: "Sainte Marie",
            code_departement: 974,
            nombre_lots: 0,
            type_local: "Appartement",
            nombre_pieces_principales: 0,
            longitude: -20.895685578343066,
            latitude: 55.56705055732452

        }
    ],
    Y_train: []
}

