name: Deploy Workflow
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '21.7.1'

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Archive build files
      run: |
        mkdir build
        cp -r .next build/
        cp package.json build/
        cp package-lock.json build/
        cp -r public build/
        tar -czvf build.tar.gz -C build .

    - name: Upload build artifact
      uses: actions/upload-artifact@v2
      with:
        name: build-artifact
        path: build.tar.gz

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download build artifact
      uses: actions/download-artifact@v2
      with:
        name: build-artifact
        path: .

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Copy build files to server
      run: |
        scp -o StrictHostKeyChecking=no build.tar.gz root@194.164.72.59:/tmp/
        ssh -o StrictHostKeyChecking=no root@194.164.72.59 << 'EOF'
        
          mkdir -p /root/app/
          tar -xzvf /tmp/build.tar.gz -C /root/app/
          cd ~/app

          # Install dependencies in production mode
          npm install --production

          # Stop the current application
          pm2 stop nextjs-app || true
          pm2 delete nextjs-app || true

          # Start the application with PM2
          pm2 start npm --name "nextjs-app" -- start -- -p 3000

          # Save the PM2 process list
          pm2 save
        EOF
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}